server:
  port: 8081

spring:
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://127.0.0.1:3306/study?useUnicode=true&characterEncoding=utf8&autoReconnect=true&zeroDateTimeBehavior=convertToNull&serverTimezone=UTC&useSSL=true
    driver-class-name: com.mysql.cj.jdbc.Driver
    initialSize: 5
    minIdle: 5
    maxActive: 20
    maxWait: 60000
    timeBetweenEvictionRunsMillis: 60000
    validationQuery: SELECT 1
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxPoolPreparedStatementPerConnectionSize: 20
    filters: stat

mybatis:
  mapper-locations: classpath:/mybatis/mapper/*.xml
  config-location:  classpath:/mybatis/config/mybatis-config.xml

# \u65E5\u5FD7
logging:
  level:
    root: info
  config: classpath:logback-spring.xml

# \u652F\u4ED8\u5B9D\u652F\u4ED8 - \u6C99\u7BB1 https://opendocs.alipay.com/common/02kkv7
alipay:
  enabled: true
  app_id: 9021000134629874
  merchant_private_key: MIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQC6asle5Xw8aCYCIxEGGag9zc25wjeAERMxmcc1kfAMVU2G+fbyejIIEICGdpGiuLZ05GDPdes9uoXVGDWm1UAvfIoSZImQoqzntuMPYIsOMds7c3Yxi1OFSAIYPgwbUW1aHYeEDkO780Y0FJJ983SkKhS45LhSC/nx7lRG+Pns6RWFMEAFNVjeBX0WLouQNGDtJIIQgLwnhKp/sG05xX9PzA8PZGDFDZ+xPvpAe44XMXUUuDDUzQCJqvNahtkOSb5P4/F3mdDjmfx4h/KZBvrJF7PxQxsYcrqtGJu6bVAqEvFoTGnaYGe+2/u18qMcl3kJ9myjuCgqGvyGAKzltzBFAgMBAAECggEAeHoZSIZBo3yfy9PD5dBhJghDA+GcIt1mLTE4SMvXevEKWMhlq9IDUajwl3Y7qxF7gdIzKwEHlm5cnhq2WesKP2ZaiYaGTX6FBn/xAPghBnx8NlDpux1TThj6mZZIFsOqS4o4EcVySx7vaSs+fb4AzTQRDmlrIkNxNsUTnIa+Zzgl3OB+LHY5ONlqXXyvq8HHHfuSO+eelvk/G7Ph3NxkN7ig8j9n1Z6NGBXhN1TTchF62VnjtYD7+YUi+5HzUVu2BlVAiNS6NHsUK1OdX9+l6vfqMDXzG3NP9Fb2bQcTUe175q6rG+jNj1R3XWYU2WgTRtbu7KiCTKEDxuzE8ClBZQKBgQDhC1zWGd9X4b9NmDD1PnJlGTOPo3NuDnl5LzsYy04TprgWgZ2vANQ8smHdir8YZ1a8q4NE5A4WlOO+Iq0WHnQh+6RxwIPln18lFuJsxLbuaSeCaEyuuQzRJC10p/Obwj8QumpdmIymx+r+NsOynMcFd50rMXHR2l6/Ejoeh4Ek3wKBgQDUDzeKdIkoS9E/f2YHdpN04zwazEvs7zzBEZTBh6zTgRvllPwU9oPlCaP+O+j20iMixVn0K5AwkSI0oKsvmMMgFdQTtjUnq6ZL3i56nturYvemqfHXBnrlJJFqoj0RVA1oK4HZtmOerm+CGzXdUwP2LJgXkaW2z8ErbEP2A3aLWwKBgB1SWK9Awbv2mvFmQgLCNy97AB/YASM22Zbzk3SgkLS4xUWRb9Use3rJFz1BZbKtTDza8Aia2kcQ8TeF1x2JrEH9Qqjbl5PklwYDHE9lthwMMWypYExnqgbZ+t43P+NshMEOOOunA7R7Wd/zjL4J9Vh+BElrcNQR6sRkgJQXvbjrAoGBAMIWl2Aa3zpJgmAaq3ijN70hCe8BE3DtWm7fN4aWNkFzBuRvIvXQ1tE3rKhRjxzxIgV+GaHYiWVaQLNoZqXurJDeSbgs6aPAgDkqRuImKapIr6AUJWwH202E1a+ChGAqzQaN45AvVihzQU4Ut401oQecsyvHO6QBrKygr+coLkTHAoGAVfvMsgc/i6IHSerW4HjyxDHT0k9WpQJFCm5J79BYacRZhfGWmL2OGYx8uCawiV//f269SUmtAw1lKrz+eB9rTgtStmnf6rvfstNmflXn8iKgpqooR3JL8hfrdyOemyVLjlZAmngEjIIcswkhZmEPbAe7NR13NFXI0Ztacq5TxJE=
  alipay_public_key: MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAnqAVxBWdpXeWheEzILKdVs+o/Bq5Lcmjy6MhMHLqBjGlIjmjks/P+EV4Q1eg8/0a1KdRCRxhWDkifuq/S3fn98mZYm/I63g/W30bAAEicboPbl6jdiQj7wIBZPT6lgSt9rHzgXRguOURDA46sOYqpZH2U05xAMkYKGKsTu7zkGt/RkgeXMJkDlG7qAc9evt2zE6cPX5KsVbxwhEKfwdfBUAE2gIo+IAlkFh6py/vSxsBXR4ZbR1oSErKip2RmMROE98+iXTpNLEZkQ04MuFhTCzQj1tsXTUe0EDovD+5WFb3LpG7Qe9hhzu2I2bvGnVUr6CVPIFukpOYUnPqc0PU3QIDAQAB
  notify_url: http://6vkhpf.natappfree.cc/api/v1/alipay/pay_notify
  return_url: http://blog.imwj.club/
  gatewayUrl: https://openapi-sandbox.dl.alipaydev.com/gateway.do
